name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiM3IyWk4iLCJvcmdhbml6YXRpb24iOiJwVjZnYiIsInRva2VuIjoiM1BuN1EifQ.Cg_ibrP1DAJL3lp7Ls8iHgasTJ3uPRBlFwTPHTQNykY }}
        with:
          args: --baseline,qodana.sarif.json